name: Lint and Format on pull

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Check Lint
        run: npm run lint:check

      - name: Format
        run: npm run format

      - name: Build App
        run: npm run build
